# Generated by Django 5.2.8 on 2025-12-07 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='target_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
