# Generated by Django 5.2.8 on 2025-12-10 04:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameroom_target_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Esperando jugadores'), ('in_progress', 'En progreso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('drawn_numbers', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'), models.Index(fields=['code'], name='game_game_code_132bf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('game_created', 'Partida creada'), ('player_joined', 'Jugador unido'), ('player_left', 'Jugador salió'), ('game_started', 'Partida iniciada'), ('number_drawn', 'Número sorteado'), ('prize_won', 'Premio ganado'), ('game_finished', 'Partida finalizada'), ('game_cancelled', 'Partida cancelada')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='game.player')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('marked', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartones', to='game.player')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_type', models.CharField(choices=[('ambo', 'Ambo (2 en fila)'), ('terno', 'Terno (3 en fila)'), ('quaterna', 'Quaterna (4 en fila)'), ('cinquina', 'Cinquina (5 en fila)'), ('tombola', 'Tombola (cartón completo)')], max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('numbers_at_win', models.JSONField(default=list)),
                ('drawn_count', models.IntegerField(default=0)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes_won', to='game.carton')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='game.player')),
            ],
            options={
                'ordering': ['awarded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['game', 'user'], name='game_player_game_id_cba2b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game')},
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['game', 'timestamp'], name='game_gameev_game_id_f8f8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['game', 'event_type'], name='game_gameev_game_id_ff708b_idx'),
        ),
        migrations.AddIndex(
            model_name='carton',
            index=models.Index(fields=['player'], name='game_carton_player__f7350e_idx'),
        ),
        migrations.AddIndex(
            model_name='prize',
            index=models.Index(fields=['game', 'prize_type'], name='game_prize_game_id_e7d879_idx'),
        ),
        migrations.AddIndex(
            model_name='prize',
            index=models.Index(fields=['player'], name='game_prize_player__fc3725_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prize',
            unique_together={('game', 'prize_type')},
        ),
    ]
